name: "Release package"

on:
  release:
    types:
      - released

jobs:
  release:
    permissions:
      contents: write
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          # - os-name: FreeBSD-x86_64
          #   runs-on: ubuntu-24.04
          #   force-use-cross: true
          #   target: x86_64-unknown-freebsd

          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            force-use-cross: true
            target: x86_64-unknown-linux-gnu

          # - os-name: Linux-aarch64
          #   runs-on: ubuntu-24.04
          #   target: aarch64-unknown-linux-musl

          # - os-name: Linux-riscv64
          #   runs-on: ubuntu-24.04
          #   target: riscv64gc-unknown-linux-gnu

          - os-name: Windows-x86_64
            runs-on: windows-latest
            force-use-cross: false
            target: x86_64-pc-windows-msvc

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            force-use-cross: false
            target: x86_64-apple-darwin

          - os-name: macOS-arm
            runs-on: macOS-latest
            force-use-cross: false
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          force-use-cross: ${{ matrix.platform.force-use-cross }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: morset
          changes-file: ""
          target: ${{ matrix.platform.target }}

  wasm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup wasm32 toolchain
        run: |
          rustup install stable
          rustup target add wasm32-unknown-unknown

      - name: Install trunk
        uses: taiki-e/install-action@v2
        with:
          tool: trunk

      - name: Build
        run: trunk build --release

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
